
from html_tag import HtmlTag

# ###################################################################
# PRE-DEFINED CLASSES
# ###################################################################

valid_html = {
    "area": {'self_closing':True},
    "base": {'self_closing':True},
    "br": {'self_closing':True},
    "col": {'self_closing':True},
    "embed": {'self_closing':True},
    "frame": {'self_closing':True},
    "hr": {'self_closing':True},
    "img": {'self_closing':True, 'inline':True},
    "input": {'self_closing':True, 'inline':True},
    "link": {'self_closing':True},
    "meta": {'self_closing':True},
    "param": {'self_closing':True},

    "a": {'inline': True},
    "abbr": {},
    "acronym": {},
    "address": {},
    "article": {},
    "aside": {},
    "audio": {},

    "b": {'inline': True},
    "bdo": {},
    "big": {},
    "blockquote": {},
    "body": {},
    "button": {'inline': True},

    "canvas": {},
    "caption": {},
    "center": {},
    "cite": {},
    "code": {},
    "colgroup": {},
    "command": {},

    "datalist": {},
    "dd": {},
    "details": {},
    "dfn": {},
    "dialog": {},
    "div": {},
    "dl": {},
    "dt": {},

    "em": {},

    "fieldset": {},
    "figure": {},
    "footer": {},
    "form": {},
    "frameset": {},

    "h1": {},
    "h2": {},
    "h3": {},
    "h4": {},
    "h5": {},
    "h6": {},
    "head": {},
    "header": {},
    "hgroup": {},
    "html": {},

    "i": {'inline': True},
    "iframe": {},
    "ins": {},
    "keygen": {},
    "kbd": {},
    "label": {},
    "legend": {},
    "li": {},

    "map": {},
    "mark": {},
    "meter": {},
    "nav": {},
    "noframes": {},
    "noscript": {},

    "ol": {},
    "optgroup": {},
    "option": {},
    "p": {},
    "pre": {},
    "progress": {},

    "q": {},
    "ruby": {},
    "rt": {},
    "rp": {},

    "s": {},
    "samp": {},
    "script": {},
    "section": {},
    "select": {'inline': True},
    "small": {'inline': True},
    "source": {},
    "span": {'inline': True},
    "strike": {},
    "strong": {},
    "style": {},
    "sub": {},
    "sup": {},

    "table": {},
    "tbody": {},
    "td": {},
    "textarea": {'inline': True},
    "tfoot": {},
    "th": {},
    "thead": {},
    "time": {},
    "title": {},
    "tr": {},
    "tt": {},

    "u": {},
    "ul": {},
    "var": {},
    "video": {},
  }
